DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
        ID BIGINT NOT NULL AUTO_INCREMENT,
        NAME VARCHAR(100) NOT NULL,
        PRIMARY KEY(ID)
);

CREATE SEQUENCE user_id_seq START WITH 1000 INCREMENT BY 1;